spring.application.name=VoteAI
spring.application.name=VoteAI

spring.datasource.url=jdbc:mysql://localhost:3306/voteai
spring.datasource.username=root
spring.datasource.password=Joshil@1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect